version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run YARN tests
          command: yarn run test
      - store_test_results:
            path: results.xml
      - store_artifacts:
            path: playwright-report/

workflows:
  test_my_app:
    jobs:
      - test
