version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

workflows:
  test_my_app:
    jobs:
      - test
